import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :log_sewer, LogSewerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lTbC3jdH1i08q8GO0xpKkxC0oB4I/pNrJ9xhUlqrTDb/JFDd1TMkEY1wAVJSN+Qk",
  watchers: []

config :log_sewer, LogSewerWeb.NaiveAuthPlug, token: "lTbC3jdH1i08q8GO0xpKkxC0oB4I/pNrJ9xhUlqrTDb/JFDd1TMkEY1wAVJSN+Qk"

# Enable dev routes for dashboard and mailbox
config :log_sewer, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# ## SSL Support

# Set a higher stacktrace during development. Avoid configuring such
#
# in production as building large stacktraces may be expensive.
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :phoenix, :stacktrace_depth, 20
